targets:
  $default:
    sources:
      - lib/models/**.dart
      - lib/providers/**.dart
      - lib/**/providers/**.dart
      - $package$
      - lib/$lib$
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: true
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          ignore_unannotated: false
          include_if_null: true
