#!/usr/bin/env python3
"""
index_fixes.py — Generate/update tools/prompts/fixes/INDEX.md from fix file headers.

Usage:
    python tools/scripts/index_fixes.py

Reads all *_fix.md files in tools/prompts/fixes/, parses standardized headers,
calculates Unlocks from tools/coverage_progress.json, and writes INDEX.md grouped
by Complexity. Entries are added/removed automatically as files appear/disappear.
Preserves the <!-- assignments --> section at the bottom of INDEX.md.
"""

import json
import re
from pathlib import Path

FIXES_DIR = Path(__file__).parent.parent / "prompts" / "fixes"
INDEX_FILE = FIXES_DIR / "INDEX.md"
COVERAGE_FILE = Path(__file__).parent.parent / "coverage_progress.json"
ASSIGNMENTS_MARKER = "<!-- assignments -->"

FIELD_RE = re.compile(r"^\*\*(.+?):\*\*\s*(.+)$")


def parse_header(path: Path) -> dict:
    fields = {"filename": path.name, "title": None}
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip()
            if not fields["title"] and line.startswith("# "):
                fields["title"] = line[2:].strip()
                continue
            if line == "---":
                break
            m = FIELD_RE.match(line)
            if m:
                fields[m.group(1).lower().replace(" ", "_")] = m.group(2).strip()
    return fields


def collect() -> list[dict]:
    files = sorted(FIXES_DIR.glob("*_fix.md"))
    return [parse_header(f) for f in files if f.name != "INDEX.md"]


def load_unlocks() -> dict[str, int]:
    """Count providers in coverage_progress.json referencing each fix file."""
    if not COVERAGE_FILE.exists():
        return {}
    with open(COVERAGE_FILE, encoding="utf-8") as f:
        data = json.load(f)
    counts: dict[str, int] = {}
    for v in data.get("providers", {}).values():
        fp = v.get("fix_proposal")
        if fp:
            filename = Path(fp).name
            counts[filename] = counts.get(filename, 0) + 1
    return counts


def group_by_complexity(entries: list[dict]) -> dict[str, list[dict]]:
    groups: dict[str, list[dict]] = {"High": [], "Medium": [], "Low": [], "Unknown": []}
    for e in entries:
        c = e.get("complexity", "Unknown")
        if c not in groups:
            c = "Unknown"
        groups[c].append(e)
    return groups


def status_badge(status: str) -> str:
    icons = {
        "blocked": "🔴",
        "partial": "🟡",
        "open": "🟡",
        "resolved": "🟢",
        "fixed": "🟢",
        "done": "🟢",
    }
    return icons.get(status.lower(), "⚪")


def load_assignments_section() -> str:
    """Return everything from <!-- assignments --> to end of existing INDEX.md, or empty section."""
    if not INDEX_FILE.exists():
        return f"{ASSIGNMENTS_MARKER}\n\n## Assignments\n\n_No assignments yet._\n"
    content = INDEX_FILE.read_text(encoding="utf-8")
    idx = content.find(ASSIGNMENTS_MARKER)
    if idx == -1:
        return f"{ASSIGNMENTS_MARKER}\n\n## Assignments\n\n_No assignments yet._\n"
    return content[idx:]


def render(groups: dict[str, list[dict]], unlocks: dict[str, int]) -> str:
    lines = [
        "# Fix Proposals — Index",
        "",
        "Auto-generated by `tools/scripts/index_fixes.py`. Do not edit manually above the assignments marker.",
        "",
        "| | Status | Unlocks | File | Reason | Type | Codegen |",
        "|--|--------|---------|------|--------|------|---------|",
    ]

    order = ["High", "Medium", "Low", "Unknown"]
    for complexity in order:
        entries = groups.get(complexity, [])
        if not entries:
            continue
        lines.append(f"| **{complexity}** | | | | | | |")
        for e in sorted(entries, key=lambda x: x["filename"]):
            status = e.get("status", "")
            badge = status_badge(status)
            filename = e["filename"]
            reason = e.get("reason", "—")
            etype = e.get("type", "—")
            codegen = e.get("codegen", "—")
            n = unlocks.get(filename, 0)
            unlocks_str = str(n) if n > 0 else "—"
            lines.append(f"| {badge} | {status} | {unlocks_str} | [{filename}]({filename}) | {reason} | {etype} | {codegen} |")

    lines.append("")
    total = sum(len(v) for v in groups.values())
    lines.append(f"*{total} files total*")
    lines.append("")
    return "\n".join(lines)


def main():
    entries = collect()
    unlocks = load_unlocks()
    groups = group_by_complexity(entries)
    assignments = load_assignments_section()
    generated = render(groups, unlocks)
    INDEX_FILE.write_text(generated + "\n" + assignments, encoding="utf-8")

    total = sum(len(v) for v in groups.values())
    print(f"INDEX.md updated: {total} files")
    for c in ("High", "Medium", "Low", "Unknown"):
        n = len(groups.get(c, []))
        if n:
            print(f"  {c}: {n}")
    total_unlocks = sum(unlocks.values())
    print(f"Unlocks tracked: {total_unlocks} provider references")


if __name__ == "__main__":
    main()
