[package]
name = "stableapp_api"
version = "0.1.0"
edition = "2021"

[dependencies]
sideswap_api = { path = "../sideswap_api" }

elements.workspace = true
serde.workspace = true
thiserror.workspace = true
