refresh_rate: 10 seconds

appenders:
  file:
    kind: rolling_file
    path: log/sideswap_testnet.log
    encoder:
      kind: pattern
      pattern: "{d(%Y-%m-%d %H:%M:%S%.3f)(utc)} {h({l})} {M} {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 100 mb
      roller:
        kind: fixed_window
        pattern: 'log/sideswap_testnet.{}.log.gz'
        base: 0
        count: 10


root:
  level: debug
  appenders:
    - file

loggers:
  ureq:
    level: info
