env = "Prod"
apikey = ""

server_url = "wss://api.sideswap.io"
status_port = 4002

bitfinexkey = "<YOUR_BITFINEX_KEY>"
bitfinexsecret = "<YOUR_BITFINEX_SECRET>"

bitfinex_withdraw_address = "<YOUR_BITFINEX_WITHDRAW_ADDR>"
bitfinex_fund_address = "<YOUR_BITFINEX_FUND_ADDR>"

work_dir = "<WORK_DIR>"
storage_path = "config/storage_prod.txt"
balancing_enabled = true

[rpc]
host = "<YOUR_ELEMENTS_HOST>"
port = 12345
login = "<YOUR_ELEMENTS_LOGIN>"
password = "<YOUR_ELEMENTS_PASSWORD>"

[notifications]
url = "" # optional slack notifications url
