env = "Testnet"
log_settings = "config/dealer_stdio_logs.yml"

bitcoin_amount_submit = 0.0001
bitcoin_amount_min = 0.0001
bitcoin_amount_max = 0.001

interest_submit = 1.01

[rpc]
host = "localhost"
port = 7041
login = "dealer"
password = "<YOUR_RPC_PASSWORD>"
