#!/usr/bin/env python3
"""
Gather metadata for a provider — uncovered lines with code snippets,
coverage%, codegen detection, fix proposal summary.

Does NOT output full file contents (subagents read files themselves).

Usage:
    python tools/scripts/gather_provider_data.py <provider.dart>

Output: JSON to stdout.
Exit code: 0 = ok, 2 = script error.
"""
import json
import subprocess
import sys
from pathlib import Path

MAX_SNIPPET_LINES = 3  # context lines around uncovered line


def run(cmd: list[str], cwd: Path, **kwargs) -> subprocess.CompletedProcess:
    return subprocess.run(
        " ".join(cmd), cwd=cwd, capture_output=True, text=True,
        encoding="utf-8", shell=True, **kwargs
    )


def detect_codegen(lib_path: Path) -> bool:
    if not lib_path.exists():
        return False
    content = lib_path.read_text(encoding="utf-8")
    return ".g.dart" in content or ".freezed.dart" in content


def get_uncovered_snippets(lib_path: Path, uncovered_lines: list[int]) -> list[dict]:
    if not lib_path.exists() or not uncovered_lines:
        return []
    lines = lib_path.read_text(encoding="utf-8").splitlines()
    snippets = []
    for line_no in uncovered_lines:
        idx = line_no - 1
        if 0 <= idx < len(lines):
            snippets.append({
                "line": line_no,
                "code": lines[idx].rstrip(),
            })
    return snippets


def get_fix_proposal_summary(stem: str, project_root: Path) -> tuple[str | None, str | None]:
    for suffix in ["_fix.md", "_fail_fix.md"]:
        path = project_root / "tools" / "prompts" / "fixes" / f"{stem}{suffix}"
        if path.exists():
            content = path.read_text(encoding="utf-8")
            # Return first 5 non-empty lines as summary
            summary_lines = [l for l in content.splitlines() if l.strip()][:5]
            return "\n".join(summary_lines), str(path.relative_to(project_root))
    return None, None


def main() -> None:
    if len(sys.argv) < 3:
        print("Usage: python <script> <project_root> <provider.dart>",
              file=sys.stderr)
        sys.exit(2)

    PROJECT_ROOT = Path(sys.argv[1]).resolve()
    provider = sys.argv[2]
    stem = provider.removesuffix(".dart")
    lib_path = PROJECT_ROOT / "lib" / "providers" / provider
    test_path = PROJECT_ROOT / "test" / "providers" / f"{stem}_test.dart"

    # Read coverage from existing lcov (generated by coverage_baseline.py at session start)
    # Does NOT run tests — uses full-suite lcov for accurate cross-file coverage
    result = run(["python", "tools/scripts/extract_coverage.py", provider], cwd=PROJECT_ROOT)
    try:
        coverage_data = json.loads(result.stdout)
    except json.JSONDecodeError:
        coverage_data = {
            "coverage_pct": None,
            "uncovered_lines": [],
            "note": "extract_coverage failed",
        }

    uncovered_lines = coverage_data.get("uncovered_lines", [])
    snippets = get_uncovered_snippets(lib_path, uncovered_lines)
    fix_summary, fix_path = get_fix_proposal_summary(stem, PROJECT_ROOT)

    report = {
        "provider": provider,
        "lib_path": f"lib/providers/{provider}",
        "test_path": f"test/providers/{stem}_test.dart",
        "test_exists": test_path.exists(),
        "coverage_pct": coverage_data.get("coverage_pct"),
        "covered": coverage_data.get("covered", 0),
        "total": coverage_data.get("total", 0),
        "uncovered_lines": snippets,
        "has_codegen": detect_codegen(lib_path),
        "fix_proposal": fix_summary,
        "fix_proposal_path": fix_path,
    }

    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
