[package]
name = "sideswap_dealer_bitfinex"
version = "0.1.0"
edition = "2021"

[dependencies]
sideswap_api = { path = "../sideswap_api" }
sideswap_common = { path = "../sideswap_common" }
sideswap_dealer = { path = "../sideswap_dealer" }

anyhow.workspace = true
tokio-tungstenite = { workspace = true, features = [ "stream" ] }
base64.workspace = true
clap.workspace = true
config.workspace = true
crossbeam-channel.workspace = true
elements = { workspace = true, features = ["serde"] }
futures-util.workspace = true
futures.workspace = true
hex.workspace = true
hyper = { workspace = true, features = ["server"] }
libc.workspace = true
log.workspace = true
log4rs = { workspace = true, features = ["gzip"] }
prost.workspace = true
rand.workspace = true
reqwest = { workspace = true, default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
signal-hook.workspace = true
tokio = { workspace = true, features = ["macros", "net", "rt", "sync", "time"] }
tungstenite = { workspace = true, default-features = false, features = [] }
url.workspace = true
ureq = { workspace = true, features = ["json"] }
ring = "0.17.7"

[build-dependencies]
prost-build.workspace = true
