[package]
name = "sideswap_dealer_bitfinex"
version = "0.1.0"
edition = "2018"

[dependencies]
sideswap_api = { version = "*", path = "../sideswap_api" }
sideswap_common = { version = "*", path = "../sideswap_common" }
sideswap_dealer = { version = "*", path = "../sideswap_dealer" }
clap = "*"
log = "*"
log4rs = { version = "*", features = ["gzip"] }
serde_json = "*"
reqwest = { version = "*", default-features = false, features = ["blocking", "json", "rustls-tls"] }
anyhow = "*"
serde = { version = "1.0", features = ["derive"] }
config = "0.11.0"
tungstenite = { version = "0.17.2", default-features = false, features = [] }
url = "*"
async-tungstenite = { version = "0.17.2", features = ["async-std-runtime", "async-tls"] }
async-std = "*"
async-tls = "*"
rustls = { version = "*", features = ["dangerous_configuration"] }
futures = "*"
futures-util = "*"
webpki = "*"
tokio = { version = "1.20.3", default-features = false, features = ["macros", "net", "rt", "sync", "time"] }
prost = "0.10.4"
libc = "*"
signal-hook = "*"
hyper = { version = "*", features = ["server"] }
elements = { git = "https://github.com/ElementsProject/rust-elements", rev = "0edddf730ff8fd441d3af28bc600b8bc8a8df5a9", features = ["serde-feature"] }
base64 = "*"
hex = "*"
rand = "0.7.3"
crossbeam-channel = "0.5.1"

[build-dependencies]
prost-build = "0.10.4"
