#!/bin/sh

for SIZE in 32 48 64 128 256
do
	xdg-icon-resource install --novendor --context apps --size $SIZE /usr/share/sideswap/icons/sideswap_logo_$SIZE.png sideswap
done

update-desktop-database

exit 0
