[package]
name = "sideswap_api"
version = "0.1.2"
edition = "2021"

[dependencies]
sideswap_types = { path = "../sideswap_types" }

elements.workspace = true
hex.workspace = true
serde.workspace = true
serde_with.workspace = true
serde_json.workspace = true
rand.workspace = true
