env = "Testnet" # SideSwap testnet server (Liquid Testnet network)
#env = "Prod" # SideSwap prod server (Liquid network)

# Work dir to store temporary files
work_dir = "/tmp/work_dir"

mnemonic = "<YOUR_MNEMONIC>"
script_variant = "wpkh" # Use "shwpkh" for legacy segwit addresses

price_stream = []

[web_server]
listen_on = "127.0.0.1:3101"
server_url = "http://127.0.0.1:3101/api"

[ws_server]
listen_on = "127.0.0.1:3102"

#[[price_stream]]
#base = "L-BTC"
#quote = "USDt"
#interest = 1.01
#source = "Binance"
