env = "Testnet" # SideSwap testnet server (Liquid Testnet network)
#env = "Prod" # SideSwap prod server (Liquid network)

# Work dir to store temporary files
work_dir = "/tmp/work_dir"

mnemonic = "<YOUR_MNEMONIC>"
script_variant = "wpkh" # Use "shwpkh" for legacy segwit addresses

# If necessary, add additional whitelisted assets here
whitelisted_assets = [
    #"78557eb89ea8439dc1a519f4eb0267c86b261068648a0f84a5c6b55ca39b66f1", # B-JDE (Liquid only)
    #"649f01bd72fbe33a70508e752044a2b0f91cf73612b70e03f337d095daa8b002", # PXTST (Testnet only)
]

price_stream = []

[web_server]
listen_on = "127.0.0.1:3101"
server_url = "http://127.0.0.1:3101/api"

[ws_server]
listen_on = "127.0.0.1:3102"

#[[price_stream]]
#base = "L-BTC"
#quote = "USDt"
#interest = 1.01
#source = "Binance"
