env = "Testnet" # SideSwap testnet server (Liquid Testnet network)
#env = "Prod" # SideSwap prod server (Liquid network)

# Work dir to store temporary files
work_dir = "/tmp/work_dir"

mnemonic = "<YOUR_MNEMONIC>"

script_variant = "wpkh" # Use "shwpkh" for legacy segwit addresses

receive_address = "" # The address that will receive L-BTC
