[package]
name = "sideswap_payjoin"
version = "0.1.2"
edition = "2021"

[dependencies]
anyhow.workspace = true
base64.workspace = true
elements.workspace = true
once_cell.workspace = true
rand.workspace = true
serde.workspace = true
ureq.workspace = true
